- type: replace
  path: /addons/name=loggr-system-metrics-agent?
  value:
    exclude:
      jobs:
      - name: smoke_tests
        release: cf-smoke-tests
    include:
      stemcell:
      - os: ubuntu-xenial
    jobs:
    - name: loggr-system-metrics-agent
      properties:
        system_metrics:
          tls:
            ca_cert: ((system_metrics.ca))
            cert: ((system_metrics.certificate))
            key: ((system_metrics.private_key))
      release: system-metrics
    name: loggr-system-metrics-agent

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=loggr-metric-scraper?
  value:
    name: loggr-metric-scraper
    properties:
      system_metrics:
        tls:
          ca_cert: ((system_metrics.ca))
          cert: ((system_metrics.certificate))
          key: ((system_metrics.private_key))
      leadership_election:
        ca_cert: "((leadership_election_client_tls.ca))"
        cert: "((leadership_election_client_tls.certificate))"
        key: "((leadership_election_client_tls.private_key))"
      metrics:
        ca_cert: "((loggr_metric_scraper_metrics_tls.ca))"
        cert: "((loggr_metric_scraper_metrics_tls.certificate))"
        key: "((loggr_metric_scraper_metrics_tls.private_key))"
        server_name: loggr_metric_scraper_metrics
    release: system-metrics

- type: replace
  path: /instance_groups/name=scheduler/instances
  value: 3

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=leadership-election?
  value:
    name: leadership-election
    properties:
      port: 7100
      tls:
        ca_cert: "((leadership_election_tls.ca))"
        cert: "((leadership_election_tls.certificate))"
        key: "((leadership_election_tls.private_key))"
      metrics:
        ca_cert: "((leadership_election_metrics_tls.ca))"
        cert: "((leadership_election_metrics_tls.certificate))"
        key: "((leadership_election_metrics_tls.private_key))"
        server_name: leadership_election_metrics
    release: system-metrics

- type: replace
  path: /variables/name=system_metrics?
  value:
    name: system_metrics
    options:
      ca: loggregator_ca
      common_name: system-metrics
      extended_key_usage:
      - client_auth
      - server_auth
    type: certificate

- type: replace
  path: /releases/name=system-metrics?
  value:
    name: system-metrics
    version: latest

- type: replace
  path: /variables/name=leadership_election_tls?
  value:
    name: leadership_election_tls
    type: certificate
    options:
      ca: loggregator_ca
      common_name: leadership_election
      extended_key_usage:
      - server_auth

- type: replace
  path: /variables/name=leadership_election_client_tls?
  value:
    name: leadership_election_client_tls
    type: certificate
    options:
      ca: loggregator_ca
      common_name: leadership_election_client
      extended_key_usage:
      - client_auth

- type: replace
  path: /variables/name=loggr_metric_scraper_metrics_tls?
  value:
    name: loggr_metric_scraper_metrics_tls
    type: certificate
    options:
      ca: metric_scraper_ca
      common_name: loggr_metric_scraper_metrics
      extended_key_usage:
      - server_auth

- type: replace
  path: /variables/name=leadership_election_metrics_tls?
  value:
    name: leadership_election_metrics_tls
    type: certificate
    options:
      ca: metric_scraper_ca
      common_name: leadership_election_metrics
      extended_key_usage:
      - server_auth