name: system-metrics-agent

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: bpm
  version: latest
- name: system-metrics
  version: latest

addons:
- name: bpm
  include:
    stemcell:
    - os: ubuntu-trusty
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: standalone-agent
  azs:
  - z1
  instances: 1
  persistent_disk_type: 5GB
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: loggr-system-metrics-agent
    properties:
      system_metrics:
        tls:
          ca_cert: ((system_metrics.ca))
          cert: ((system_metrics.certificate))
          key: ((system_metrics.private_key))
    release: system-metrics

  - name: loggr-metric-scraper
    properties:
      leadership_election:
        ca_cert: ((leadership_election_client_tls.ca))
        cert: ((leadership_election_client_tls.certificate))
        key: ((leadership_election_client_tls.private_key))
      metrics:
        ca_cert: ((loggr_metric_scraper_metrics_tls.ca))
        cert: ((loggr_metric_scraper_metrics_tls.certificate))
        key: ((loggr_metric_scraper_metrics_tls.private_key))
        server_name: loggr_metric_scraper_metrics
      system_metrics:
        tls:
          ca_cert: ((system_metrics.ca))
          cert: ((system_metrics.certificate))
          key: ((system_metrics.private_key))
    release: system-metrics

  - name: leadership-election
    properties:
      metrics:
        ca_cert: ((leadership_election_metrics_tls.ca))
        cert: ((leadership_election_metrics_tls.certificate))
        key: ((leadership_election_metrics_tls.private_key))
        server_name: leadership_election_metrics
      port: 7100
      tls:
        ca_cert: ((leadership_election_tls.ca))
        cert: ((leadership_election_tls.certificate))
        key: ((leadership_election_tls.private_key))
    release: system-metrics

variables:
- name: system_metrics
  options:
    ca: loggregator_ca
    common_name: system-metrics
    extended_key_usage:
    - client_auth
    - server_auth
  type: certificate

- name: loggregator_ca
  type: certificate
  options:
    common_name: loggregatorCA
    is_ca: true

- name: leadership_election_client_tls
  options:
    ca: loggregator_ca
    common_name: leadership_election_client
    extended_key_usage:
    - client_auth
  type: certificate

- name: loggr_metric_scraper_metrics_tls
  options:
    ca: metric_scraper_ca
    common_name: loggr_metric_scraper_metrics
    extended_key_usage:
    - server_auth
  type: certificate

update:
  canaries: 10
  max_in_flight: 10
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: true
